version: '3'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: zhouzeqiang.github.io # 这里是我镜像的名字
    ports:
      - 4000:4000
    volumes:
      - /var/jekyll/www/html:/var/jekyll/www/html
    network_mode: host
    working_dir: /blog